/*
 Generated by typeshare 1.13.3
*/

export interface CreateUserRequest {
  email: string;
  name: string;
}

export interface User {
  id: number;
  email: string;
  name: string;
  created_at: string;
}
