name: Publish to crates.io
on:
    push:
        tags: ["v*"] # Triggers when pushing tags starting with 'v'
jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            id-token: write # Required for OIDC token exchange
            contents: read
        steps:
            - uses: actions/checkout@v5

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Verify version matches tag
              run: |
                  TAG_VERSION=${GITHUB_REF#refs/tags/v}
                  CARGO_VERSION=$(grep '^version' Cargo.toml | head -1 | cut -d'"' -f2)
                  if [ "$TAG_VERSION" != "$CARGO_VERSION" ]; then
                    echo "❌ Tag v$TAG_VERSION doesn't match Cargo.toml version $CARGO_VERSION"
                    exit 1
                  fi
                  echo "✅ Version check passed: $CARGO_VERSION"

            - name: Run tests
              run: cargo test --all-features

            - name: Check build
              run: cargo check --all-features

            - name: Authenticate with crates.io
              uses: rust-lang/crates-io-auth-action@v1
              id: auth

            - name: Publish to crates.io
              run: cargo publish
              env:
                  CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
